// Command aidocs generates the compact LLM entry points and skill references
// from docs/ai, which is the single maintained documentation source.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

var sections = []struct {
	file  string
	title string
}{
	{file: "overview.md", title: "Overview and core rules"},
	{file: "api-reference.md", title: "Complete public API reference"},
	{file: "recipes.md", title: "Test-generation recipes"},
	{file: "constraints.md", title: "Generation constraints and review checklist"},
}

func main() {
	check := flag.Bool("check", false, "fail if generated files are stale")
	flag.Parse()

	root, err := findRoot()
	if err != nil {
		fatal(err)
	}
	outputs, err := render(root)
	if err != nil {
		fatal(err)
	}
	for path, content := range outputs {
		if *check {
			actual, readErr := os.ReadFile(path)
			if readErr != nil || !bytes.Equal(actual, content) {
				fatal(fmt.Errorf("generated AI documentation is stale: %s; run go generate ./internal/aidocs", path))
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fatal(err)
		}
	}
}

func findRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repository root from %s", dir)
		}
		dir = parent
	}
}

func render(root string) (map[string][]byte, error) {
	contents := make(map[string]string, len(sections))
	for _, section := range sections {
		data, err := os.ReadFile(filepath.Join(root, "docs", "ai", section.file))
		if err != nil {
			return nil, err
		}
		contents[section.file] = strings.TrimSpace(string(data))
	}

	var index strings.Builder
	index.WriteString("# testx\n\n")
	index.WriteString("> LLM documentation for github.com/go-testx/testx (Go 1.23+).\n\n")
	index.WriteString("testx layers typed assertions, declarative Cases, presets, contracts, polling, HTTP/CLI helpers, golden files, benchmarks, and fuzz seeds on Go's standard testing package. Assertions report failures themselves; do not wrap them in if + Fatal/Error. RunErr expects no error unless a Case uses WithError.\n\n")
	index.WriteString("## Documentation\n\n")
	for _, section := range sections {
		fmt.Fprintf(&index, "- [/%s](docs/ai/%s): %s.\n", section.file, section.file, section.title)
	}
	index.WriteString("- [/README.md](README.md): Human-oriented full project documentation, installation, and IDE tooling.\n\n")
	index.WriteString("## Quick generation rules\n\n")
	index.WriteString("1. Keep standard func TestXxx(t *testing.T) tests.\n")
	index.WriteString("2. Use Require for prerequisites and Assert for independent checks.\n")
	index.WriteString("3. Never add t.Fatal/t.Error after a failed testx assertion; it already reported.\n")
	index.WriteString("4. Match Run, RunErr, or ContextFuncErr to the exact subject signature.\n")
	index.WriteString("5. Do not invent APIs or business fixtures; fall back to standard testing when needed.\n")

	var full strings.Builder
	full.WriteString("# testx complete LLM documentation\n\n")
	full.WriteString("Generated from docs/ai. Do not edit this file directly.\n")
	for _, section := range sections {
		full.WriteString("\n---\n\n")
		full.WriteString(contents[section.file])
		full.WriteByte('\n')
	}

	references := map[string][]byte{}
	for _, section := range sections {
		header := "<!-- Generated from docs/ai/" + section.file + ". Do not edit directly. -->\n\n"
		references[filepath.Join(root, "skills", "testx", "references", section.file)] = []byte(header + contents[section.file] + "\n")
	}

	outputs := map[string][]byte{
		filepath.Join(root, "llms.txt"):      []byte(index.String()),
		filepath.Join(root, "llms-full.txt"): []byte(full.String()),
	}
	for path, content := range references {
		outputs[path] = content
	}
	return outputs, nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "aidocs:", err)
	os.Exit(1)
}
